name: 'create reminder'

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Create Reminder
        uses: agrc/create-reminder-action@72569089eed4baead9e6fa7613ab51534cd1fba3