name: 'check reminders (hourly)'

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Issue Reminder
      uses: kublaios/reminder-action@453ef8ea57a18f4e2a1bee3b29c40a5b8782c674
