name: 'check reminders'

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Issue Reminder
      uses: agrc/reminder-action@v1.0.1
